name: React_Food_App_CI

on: [push]

jobs:
  Sast_Scan:
    name: Run Sonar Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Setup Node JS
      uses: actions/setup-node@v4.2.0
      with:
        node-version: 21

    - name: Install dependencies
      run: npm install

    - name: Setup Sonar Qube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npm install -g sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=react-devsecops \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://13.233.197.39:9000 \
          -Dsonar.login=$SONAR_TOKEN

    - name: Install GitLeaks 
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.16.1/gitleaks_8.16.1_linux_x64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin

    - name: Run GitLeaks Scan
      run: |
        gitleaks detect \
          --redact \
          --exit-code=2 \
          --report-format=sarif \
          --report-path=gitleaks-report.sarif \
          --log-level=debug

  Docker_Build_Trivy_Scan:
    name: Docker Build and Image Scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Building the image
      run: docker build -t food-app-react:latest .

    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: food-app-react:latest
        format: table
        severity: CRITICAL,HIGH

    - name: Login to DockerHUB
      uses: docker/login-action@v3.4.0
      with:
        Username: ${{ secrets.DOCKER_USERNAME }}
        Password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Image to DockerHUB
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/food-app-react:latest

    - name: Upload Trivy Scan Report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:  
        name: trivy-report
        path: trivy-report.txt
